language: cpp
sudo: required
before_install:
- export DEVKITPRO=/home/travis/devkitPro
- export DEVKITARM=${DEVKITPRO}/devkitARM
- export CTRULIB=${DEVKITPRO}/libctru
- sh .travis-deps.sh
script:
- cd src
- make clean
- make
before_deploy:
- cd src
- zip dev *.3dsx *.smdh
- cd ..
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-rev$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "3ds.js development build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GH_TOKEN@github.com/filfat-Studios-AB/3ds.js --tags
- ls -R
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QDV8v5ayUtaTaO6pOZ0UX3AAKElIM1oYMTqRHT9EmhQ21IjvZFzN6m96yfNRb8G/58qzJ18BrbnQ2DOl9555f/avdfFbD2/0olh37VHrCLbhTEmxUKXLmhmRoKEc3sUeh7HS+j6kL5IiY/cvcaN6BrHa0o/HEh5pzCGzLxc0okSvsnM6DwO+SqF3z+lifabBrAxFJLpjulfsiyxOI+sVkMS4v4Q8nqRmedExZjoKdpJNpusMd0qCIztEfma4yCvqMkLPmkKoCpJ3FGMCbj9quiQoh2jm8tKQcVk+/DtjsFS/mwNuTWLFuHzuVfq/Jwf8rYuQYzQgmir1bTj/6SH6dfoxs29nq5MX0pu/fhMN86XHDGDRJMxqvYDbyCOnwESrQh1E/n1nxk+cv2Y7YsNZ5aouyjAv9SeSg1vSpwLzj6pPB7VKDLSyc2nD90FysOr6rVW0wFMni7sUym2w6PIRIXps8pHXolT6vMM0L2wWNdpvKTNLsqNgpKGk6doo3UJqzV8GtNls5jBOfKtbneY+IyBabaN8CgxEymCsdW7KvAAz32N5LyNWhoj2bZ7+SceFyiDS24WPnMmuikhaNkTLZ8yyWg9IyYQc1O8wIvPXFYPyiL0IDw7speJkmNTF805YO2+3B4H3s69A4jiifRTEgJ62Ch1pFP/j7fI8MWCDRMA=
  file: "src/dev.zip"
  on:
    tags: false
    repo: filfat-Studios-AB/3ds.js
    all_branches: true
branches:
  except:
  - "/^*-rev[0-9]/"
env:
  global:
    secure: G4AZzJR2j4lpAs7t+bdjyzScEntEXzrSl0B0tGU2/36hGV6Xte3HhiC+OadIAS9NBcO5bstzNI8xcL1zPGXkMgDquTddLL3KbeIUj7eK3XclIqplPkBt341q1OhQUCAQ1YF2NESsJNMtVWzetEVL8OdwEaGbr3mE24fmpry+borM+Uf+fY166CZk7gpZTbwD/Hj6odnyTnz5kf92GgMWbSHDOja61tMP0Q7QRiDMjghmZRS9TEHN4zVL7AM+lE2na7l7MqiNReGnLMYtO0YFmhA/P/Nn11f50hobCBcoLoEG834kayHak3yRJQjSMda4Nlt5gTDhKJxT5jLmtmaMmfp6KpGHNnFB2bqslm4+7veuWy3ZR44cAV2iGFTUJIi7WxJA2jmeE0LWIEbBFFuHbcOt4kp1r69esmhgdULX7kXrxWeNjqP/hbNXx2R9El/0pmDIzk7PZfL8sJayJ4MjuU2MR/RWSWTbf6ocJygVBBmsM1DPjtxz6RObdJpPnFylbqsUtuLMU7nQMov+4elMutkzFX8X6iXBPW8Bk+d28qO6Ahn7qfKjgyzQEe9Y+fSp6jn7jvEdSIg9ySMSYUg8CO8hhOkHyvP3yZiZKskmMIBBY17KXAjR646F/Ma8v9yEfPciEHhrhN1LUns7McWL+0OPUbufjQFlumHqXr9LuCU=
