language: cpp

sudo: required

before_deploy:
  - zip dev *.3dsz *.smdh

before_install:
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export CTRULIB=${DEVKITPRO}/libctru
  - sh .travis-deps.sh

script:
  - cd src
  - make clean
  - make
